events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # ─── Staff paneli: port 80 ──────────────────────────────
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html/staff;
        index index.html;

        # API so'rovlarini backend ga yo'naltirish
        location /api/ {
            proxy_pass         http://panel:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    # ─── Guest paneli: port 81 ──────────────────────────────
    server {
        listen 81;
        server_name _;
        root /usr/share/nginx/html/guest;
        index login.html;

        # API so'rovlarini backend ga yo'naltirish
        location /api/ {
            proxy_pass         http://panel:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /login.html;
        }
    }
}
